//企业类型
var CODE_ENT_TYP = {
    CODE_ENT_TYP_JY : "JY",
    CODE_ENT_TYP_GNSC : "GNSC",
    CODE_ENT_TYP_GWSC : "GWSC",
    CODE_ENT_TYP_KD : "KD",
    CODE_ENT_TYP_YL : "YL",
    CODE_ENT_TYP_ZT : "ZT"
};

//首营状态
var FIRSTSTATE = {
    FIRSTSTATE_00 : "00",
    FIRSTSTATE_10 : "10",
    FIRSTSTATE_40 : "40",
    FIRSTSTATE_50 : "50",
    FIRSTSTATE_60 : "60",
    FIRSTSTATE_90 : "90"
}

//审核
var CHECKSTATE = {
    CHECKSTATE_00 : "00",
    CHECKSTATE_20 : "20",
    CHECKSTATE_30 : "30",
    CHECKSTATE_40 : "40",
    CHECKSTATE_50 : "50"
}


